### ISSUE TITLE
YouTube Music Feature request

### ISSUE THREAD

**Issue by prjcarr** [bushvin/hass-integrations#10]
Would you consider adding support for the YouTube Music plugin? https://github.com/OzymandiasTheGreat/mopidy-ytmusic

Thanks

**Comment by bushvin** [comment]
I will see what I can do.
Don't expect anything tomorrow ;)

**Comment by bushvin** [comment]
I've checked, and it turns up normal once installed server-side.

Things that don't work at first glance:
- playing playlists

Things which appear to work out-of-the-box:
- playing albums
- playing individual tracks

Should you come over other things, could you please complete?
