### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by prjcarr** [bushvin/hass-integrations#12]
I have noticed that if I play a song from a playlist directly in Mopidy (webclient) the HA media player shows the progress bar, however if I do the same thing via search in the webclient, there is no progress bar in HA. 

Not sure if this is a bug?

Really great job on this integration by the way!

**Comment by prjcarr** [comment]
This might actually be an issue with the Mopidy youtube music integration, as I just noticed its doing the same thing in the Iris and Musicbox web clients.

**Comment by bushvin** [comment]
I'll see if I find anything, but I doubt it's the integration, as the data comes straight from the Mopidy API. I don't do anything different based on `source` (ie spotify, local, ...)
