### ISSUE TITLE
Setup.py Error | Platform not found

### ISSUE THREAD

**Issue by ConfusedAlex** [bushvin/hass-integrations#19]
I follwed the instructions but when I added the Mopidy Server I got this error in my notifications.

`Unable to prepare setup for platform mopidy.media_player: Platform not found (cannot import name 'async_process_play_media_url' from 'homeassistant.components.media_player' (/usr/src/homeassistant/homeassistant/components/media_player/__init__.py)).`

**Comment by bushvin** [comment]
Hey,

I only manage the mopidy media player component for HA, not the [Mopidy Server add-on](https://github.com/hassio-addons/addon-mopidy)
or am I missing something?

**Comment by ConfusedAlex** [comment]
I don't have the Mopdiy Server add-on installed. I run Mopidy on an Raspberry Pi and tried to connect from Home Assistant to the Raspberry Pi.

Do I need this add-on?

**Comment by bushvin** [comment]
No, you definitely do not need this add-on when running my integration, just a working mopidy instance.

Would you happen to have more errormessage? References to lines in code, etc.

Could you also include a (redacted) copy of your mopidy server config?

**Comment by ConfusedAlex** [comment]
I completely misunderstand this integration. I am sorry for creating this issue, that was caused by my misunderstanding.
