### ISSUE TITLE
Homeassistant CORE 

### ISSUE THREAD

**Issue by shahglobal** [bushvin/hass-integrations#20]
Hi,
Is there any instructions to install mopidy media player in homeassistant CORE setup.  I want to play local mp3 files from pi 
 through 3.5mm audio jack as notifications. Thanks

**Comment by abelmatser** [comment]
This repo creates a client to interface with a pre-existing Mopidy server, so no, it in no way installs the Mopidy server in Home Assistant Core, nor will that happen in the future in this repo.

**Comment by bushvin** [comment]
like @abelmatser stated, this is a integration, not an add-on.
If you would like to add Mopidy to your HA instance, please have a look at [addon-mopidy](https://github.com/hassio-addons/addon-mopidy)
