### ISSUE TITLE
Mopidy restore on youtube doesn't work

### ISSUE THREAD

**Issue by Chreece** [bushvin/hass-integrations#21]
Hello,

First of all, thank you very much for your time. It's a great project, already a part of my daily routine.
I'm using the Mopidy-Youtube. I have noticed that the snapshot / restore service doesn't work.
After the restore the song goes back to the start and not at the saved position.

**Comment by bushvin** [comment]
I made a ton of changes in my 2.x release. Could you please check?

**Comment by Switch123456789** [comment]
My guess is it is related to a bug in `mopidy-youtube` that broke seeking in general. A fix has already been merged but it is not included in the pip-release. I installed the extension directly from the `develop` branch and seeking works now.
Here is a way to install the extension from the `develop`-branch:
```
wget "https://github.com/natumbri/mopidy-youtube/archive/refs/heads/develop.zip" -P "/tmp"
unzip "/tmp/develop.zip" -d "/tmp"
cd "/tmp/mopidy-youtube-develop"
pip3 install .
```

**Comment by bushvin** [comment]
closing as there's no response from OP.
