### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by AndrewSpec** [bushvin/hass-integrations#23]
I'm using latest HA inside VM on Proxmox and I saw many mopidy integration errors in HA logs:

> Mopidy connection error: HTTPConnectionPool(host='mopidy.local', port=6680): Max retries exceeded with url: /mopidy/rpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7084b16200>: Failed to establish a new connection: [Errno 22] Invalid argument'))

After some testing: mopidy server is working fine, HA is working fine - I am able to use the dashboard at any time (no connection issues).

**Comment by xmaxzzz** [comment]
Same problem (

**Comment by bushvin** [comment]
I realise this is a bit late, but are you still experiencing these issues?

This issue would mean there is no mopidy instance on mopidy.local @ port 6680
It might also mean your dns cannot resolve mopidy.local for some reason. Did you enter the hostname yourself, or was it picked up by the integration?

**Comment by AndrewSpec** [comment]
> I realise this is a bit late, but are you still experiencing these issues?
> 
> This issue would mean there is no mopidy instance on mopidy.local @ port 6680
> It might also mean your dns cannot resolve mopidy.local for some reason. Did you enter the hostname yourself, or was it picked up by the integration?

I made some tweaks to my home dns and it's working without any issues.
