### ISSUE TITLE
Play/Stop music in automation

### ISSUE THREAD

**Issue by rafalolb** [bushvin/hass-integrations#24]
Hello,

I want to only play music in my automation (I have selected music file before). In my automation I choose "Add action -> call service" and I have only "mopidy.restore", "mopidy.search", "mopidy.snapshot". I don't see mopidy.play, mopidy.pause (for stop plaing).

Please help.

**Comment by bushvin** [comment]
The mopidy integration can be controlled by the regular [media_player](https://www.home-assistant.io/integrations/media_player/) services
