### ISSUE TITLE
Mopidy freezed after choose TTS or Radio in Home Assistant 

### ISSUE THREAD

**Issue by petrklic16** [bushvin/hass-integrations#25]
Hi,

i would like to ask you.
I have Odroid device with Home Assistant (newest version) and connected speaker over 3,5mm jack.
I’ve installed Mopidy and it’s working fine, but…

it’s not possible to udpate it (it’s not main problem)
If i choose TTS or Radio from Media, Mopidy freezed…
I’ve created short video to describe my problem

[https://youtu.be/NipPb9csjQA](https://github.com/Poeschl/Hassio-Addons/issues/url)

Can you help me please?
And i would like to install spotify extension but i dont know how i can do it 😦 in Home Assistant

Thank you so much

**Comment by bushvin** [comment]
Hey,

what you are experiencing is not related to my integration. My integration only provides an interface to HA from Mopidy.

that being said…
You have installed the mopidy add-on so you are limited to what the add-on can do. For instance, upgrading iris, or installing pip will not be possible. But if you have questions related tot the add-onn, please raise issues in that repo: https://github.com/hassio-addons/addon-mopidy

in fact all issues you raise are related to the engine and not this integration.
