### ISSUE TITLE
Integration not working after upgrade to 2023.8.0

### ISSUE THREAD

**Issue by astraliens** [bushvin/hass-integrations#29]
After upgrade to 2023.8.0 integration not working anymore.
After delete and create new mopidy entity it creating empty item without any entities
Also there is nothing interesting in log.
Existing entities added before just unavailable.

**Comment by bushvin** [comment]
Thank you for reporting this issue.
I will not be able to work on it for the next 2-3 weeks, unfortunately...

So please be patient.

**Comment by bushvin** [comment]
Really no idea. I would first turn on logging for the integration and restart HA.
Hopefully that would come up with some lead as to where it went wrong.
If not, scour the HA developers documents for stuff that was recently introduced, and possibly compare to other integrations as to what they did...

**Comment by astraliens** [comment]
In changelog to new HA version mentioned "Python 3.10 support has previously been deprecated and has now been removed. Home Assistant now requires Python 3.11 to run."
Maybe something broken due to this update

**Comment by paolapersico1** [comment]
I think the issue was due to this commit: https://github.com/home-assistant/core/pull/96479/commits/0e29ec5a985d7c2648d9dc780ef9f0fdb715ad6f.
 I created a pull request for the fix (it's my first open-source contribution, please tell me if I should have done it differently)

**Comment by tanishqmanuja** [comment]
Thank you, no error now. I guess we should merge this.

**Comment by bushvin** [comment]
@paolapersico1 good catch!

**Comment by astraliens** [comment]
> @paolapersico1 good catch!

don't forget to make new release after merge, so autoupdate in HA will get new fixed version for everyone

**Comment by bushvin** [comment]
Thank you, all, for helping out in fixing this.
Pushing a new release through termux works... 😃 : 1.5.0 is available!
