### ISSUE TITLE
A clarification

### ISSUE THREAD

**Issue by ebiscaia** [bushvin/hass-integrations#32]
Hi,

One thing that I would like to understand. Is your integration meant to control mopidy servers using HomeAssistant, right? For example, I have mopidy installed in my notebook and if I add to the integration its IP and hostname, i would be able to control from any device I can access HA. This is not meant for example to Mopidy being able to be played in Alexa or Chromecast?

Thanks

**Comment by bushvin** [comment]
Hello @ebiscaia ,

This integration is indeed meant to have Home Assistant control your Mopidy instance. It provides a `media_player` interface to the Mopidy api, which you can then control through the dashboard, scripts and/or automations.

I have, for example, an automation which starts playing music at 7:00 to wake me up.

Hope this answers your questions.

**Comment by ebiscaia** [comment]
@bushvin,

Thanks for clarifying that.
