### ISSUE TITLE
[Feature request] Consume-switch

### ISSUE THREAD

**Issue by Switch123456789** [bushvin/hass-integrations#33]
Having the ability to enable/disable "consume" would be very beneficial (for me). Do you think you could add that as a switch or something? Great integration btw, I make great use of it every day :)

**Comment by bushvin** [comment]
Hi @Switch123456789 ,

Not sure what you mean by a "Consume" switch.

**Comment by bushvin** [comment]
Found it, it is in the API. I feared it was in iris.
It should be feasible to implement it easily...

**Comment by bushvin** [comment]
fixed with #34

**Comment by Switch123456789** [comment]
Awesome, thank you man! =)
