### ISSUE TITLE
TTS Play

### ISSUE THREAD

**Issue by mhetzi** [bushvin/hass-integrations#40]
Hi,
Since the last update I am getting this error:

Nov 02 09:29:10 xeon.lan hass[71464]: NameError: name 'uri' is not defined
Nov 02 09:29:10 xeon.lan hass[71464]: 2023-11-02 09:29:10.397 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139691233432896] Error handling message: Unknown error (unknown_error) marcel from 192.168.55.1 (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36)
Nov 02 09:29:10 xeon.lan hass[71464]: Traceback (most recent call last):
Nov 02 09:29:10 xeon.lan hass[71464]:   File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
Nov 02 09:29:10 xeon.lan hass[71464]:     await func(hass, connection, msg)
Nov 02 09:29:10 xeon.lan hass[71464]:   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 731, in handle_execute_script
Nov 02 09:29:10 xeon.lan hass[71464]:     script_result = await script_obj.async_run(msg.get("variables"), context=context)
Nov 02 09:29:10 xeon.lan hass[71464]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 02 09:29:10 xeon.lan hass[71464]:   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1578, in async_run
Nov 02 09:29:10 xeon.lan hass[71464]:     return await asyncio.shield(run.async_run())
Nov 02 09:29:10 xeon.lan hass[71464]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 02 09:29:10 xeon.lan hass[71464]:   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
Nov 02 09:29:10 xeon.lan hass[71464]:     await self._async_step(log_exceptions=False)
Nov 02 09:29:10 xeon.lan hass[71464]:   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
Nov 02 09:29:10 xeon.lan hass[71464]:     self._handle_exception(
Nov 02 09:29:10 xeon.lan hass[71464]:   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 493, in _handle_exception
Nov 02 09:29:10 xeon.lan hass[71464]:     raise exception
Nov 02 09:29:10 xeon.lan hass[71464]:   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
Nov 02 09:29:10 xeon.lan hass[71464]:     await getattr(self, handler)()
Nov 02 09:29:10 xeon.lan hass[71464]:   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
Nov 02 09:29:10 xeon.lan hass[71464]:     response_data = await self._async_run_long_action(
Nov 02 09:29:10 xeon.lan hass[71464]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 02 09:29:10 xeon.lan hass[71464]:   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
Nov 02 09:29:10 xeon.lan hass[71464]:     return long_task.result()
Nov 02 09:29:10 xeon.lan hass[71464]:            ^^^^^^^^^^^^^^^^^^
Nov 02 09:29:10 xeon.lan hass[71464]:   File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
Nov 02 09:29:10 xeon.lan hass[71464]:     response_data = await coro
Nov 02 09:29:10 xeon.lan hass[71464]:                     ^^^^^^^^^^
Nov 02 09:29:10 xeon.lan hass[71464]:   File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
Nov 02 09:29:10 xeon.lan hass[71464]:     return await target(service_call)
Nov 02 09:29:10 xeon.lan hass[71464]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 02 09:29:10 xeon.lan hass[71464]:   File "/usr/src/homeassistant/homeassistant/components/tts/legacy.py", line 147, in async_say_handle
Nov 02 09:29:10 xeon.lan hass[71464]:     await hass.services.async_call(
Nov 02 09:29:10 xeon.lan hass[71464]:   File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
Nov 02 09:29:10 xeon.lan hass[71464]:     response_data = await coro
Nov 02 09:29:10 xeon.lan hass[71464]:                     ^^^^^^^^^^
Nov 02 09:29:10 xeon.lan hass[71464]:   File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
Nov 02 09:29:10 xeon.lan hass[71464]:     return await target(service_call)
Nov 02 09:29:10 xeon.lan hass[71464]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 02 09:29:10 xeon.lan hass[71464]:   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
Nov 02 09:29:10 xeon.lan hass[71464]:     return await service.entity_service_call(
Nov 02 09:29:10 xeon.lan hass[71464]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 02 09:29:10 xeon.lan hass[71464]:   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
Nov 02 09:29:10 xeon.lan hass[71464]:     response_data = await _handle_entity_call(
Nov 02 09:29:10 xeon.lan hass[71464]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 02 09:29:10 xeon.lan hass[71464]:   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
Nov 02 09:29:10 xeon.lan hass[71464]:     result = await task
Nov 02 09:29:10 xeon.lan hass[71464]:              ^^^^^^^^^^
Nov 02 09:29:10 xeon.lan hass[71464]:   File "/config/custom_components/mopidy/media_player.py", line 312, in async_play_media
Nov 02 09:29:10 xeon.lan hass[71464]:     uri.startswith("https://www.youtube.com/")
Nov 02 09:29:10 xeon.lan hass[71464]:     ^^^
Nov 02 09:29:10 xeon.lan hass[71464]: NameError: name 'uri' is not defined

**Comment by bushvin** [comment]
Apologies.shouild be fixed now
