### ISSUE TITLE
Add service: media_player.shuffle_set & media_player.repeat_set

### ISSUE THREAD

**Issue by Switch123456789** [bushvin/hass-integrations#44]
![image](https://media.tenor.com/MHkQjhVaMR4AAAAi/is-for-me-certified-bruh-moment.gif)

**Comment by bushvin** [comment]
I should start to charge you for these requests... ;)

I'll look into this once I have my async `media_player` update finished

**Comment by bushvin** [comment]
hold on..
just checked:
- `media_player.shuffle_set` works
- `media_player.repeat_set` works

What's the issue?

**Comment by Switch123456789** [comment]
I am sorry :D if I would have the skills to do it I wouldn't bother you.

It does work indeed, I think it wasn't working in v2.0.1 but with the latest version it works fine, weird. I have to keep an eye on it. Before when I tried to call the service, the mopidy entity didn't show up as option as if it doesn't support those service calls, when I forced it, I got an error emphasizing the same cause.

I will add it back to my setup an test it real hard :P

**Comment by bushvin** [comment]
I do remember some issues with v2.0.1, maybe they interfered. Anyway, I will close this incident, feel free to repoen if something goes wrong.

**Comment by Switch123456789** [comment]
I just figured out why a whole bunch of stuff keeps breaking for me. Whenever I play a http-stream, that's when some services become unavailable in the integration. As far as I can tell only those 2 from the OP are affected.

**Comment by bushvin** [comment]
I believe I know why...

The integration offers different `features` depending on whether the media is a stream or not. I figured a stream would be a `radio` or at least never-ending.

It appears my assumption was wrong.

Will fix ASAP, but can't today.

**Comment by bushvin** [comment]
Well, what do you know... Termux and vim actually work very well.

The issue should be solved with #52

I also released a new version with that.

**Comment by Switch123456789** [comment]
Man, I appreciate your commitment :) no hurry, it is not like you are charging me (yet) :laughing: 
I did some quick testing and so far no problem, except (but that is another issue), sometimes when I activate a playlist, the integration doesn't report that a playlist is playing, this might be mopidy related but I can't remember having this issue with v1.

**Comment by bushvin** [comment]
cool, at least something's working here... ;)
Feel free to raise an issue for the playlists, but please make sure to include the extension used with the playlists. the way to handle playlists can differ by extension... 
(Makes me wonder if I shouldn't look into creating a template for issues)
