### ISSUE TITLE
Issues with true/false values within attributes

### ISSUE THREAD

**Issue by Switch123456789** [bushvin/hass-integrations#61]
Some attributes return `on`/`off` and some return `true`/`false`.
![image](https://github.com/bushvin/hass-integrations/assets/25269380/3e8be550-c837-4623-8630-d13931b59269)
The true/false values cause issues when I use conditions in scripts, because these states aren't recognized by HA if i put them in quotation-marks. I can work around that by removing them manually but this disables the ui-editor.
![image](https://github.com/bushvin/hass-integrations/assets/25269380/4a46a215-d892-4bfb-a6cc-b113bfb6d9d5)
I guess HA doesn't like booleans in attribute-values and persists on having strings (on/off).

**Comment by bushvin** [comment]
This has actually nothing to do with the integration, rather the way the state condition is implemented.
When you look at [this article](https://www.home-assistant.io/docs/scripts/conditions/), you can see there is a condition for numeric state, and "regular" state, no boolean state.
The actual [code itself](https://github.com/home-assistant/core/blob/dev/homeassistant/helpers/condition.py#L536) is clear on the matter. It accepts strings or lists of strings.
So, I am afraid you will need to either use a [template condition](https://www.home-assistant.io/docs/scripts/conditions/#template-condition) or use `'on'` for `true` or `'off'` for `false`

**Comment by Switch123456789** [comment]
Hey thank you for clarifying! Sorry for the delay, I was pretty busy recently.

That's the thing, `'on'` & `'off'` doesn't work with conditions but `true` & `false` does for whatever reason (even if not officially supported). So my scripts works fine with the action I screenshoted. From my example, only `repeat` works properly because it returns `on` or `off`, instead of `true` or `false`.
