### ISSUE TITLE
Error in HA logs - No image_url found

### ISSUE THREAD

**Issue by paszczaq** [bushvin/hass-integrations#62]
Hi,
from long time I'm seeing this error in my HA instance - its just warning so everything seems to function but i'm curiuos how to fix it or maybe ist some kind of bug?
the number of events increases every moment

```
Ten błąd pochodzi z niestandardowej integracji.

Logger: custom_components.mopidy.speaker
Source: custom_components/mopidy/speaker.py:192
Integration: Mopidy (documentation, issues)
First occurred: 00:36:38 **(4709 occurrences)**
Last logged: 13:16:23

No image_url found for https://stream.rcs.revma.com/ye5kghkgcm0uv
```

Basically i'm using mopidy (iris frontned) with snapcast server and client using to stream internet radio using official links below:

https://stream.radio357.pl/
http://live.r357.eu/

Mopidy 3.4.1
Mopidy component 2.2.1

HA OS:
Core: 2023.12.1
Supervisor: 2023.11.6
Operating System: 11.2
Interfejs użytkownika: 20231208.2

**Comment by bushvin** [comment]
Hello @paszczaq ,

radio streams through a url (not a service like TuneIn) do not have images embedded. So in this case I am sorry, but there is nothing I can do about it.
It is a warning raised by my integration, and not considered bad enough to stop the player from playing.

This is probably not the answer you wanted to get, but I am afraid I cannot solve this.
