### ISSUE TITLE
Entity goes unavailable for a split second when changing volume

### ISSUE THREAD

**Issue by Sjorsa** [bushvin/hass-integrations#67]
When changing the volume, the card shows unavailable for a split second. The logbook also shows this.

![image](https://github.com/bushvin/hass-integrations/assets/40437966/55b8e0e8-e88d-488d-9a52-77e1c386b283)

**Comment by bushvin** [comment]
Should be fixed with ec70ab098967845e03c684779f94824104513111, available in v2.3.3

**Comment by Switch123456789** [comment]
I tested it, unfortunately the behavior didn't change. I also noticed that this happens with all kind of actions sometimes. For example play, pause & skip track.

**Comment by bushvin** [comment]
Initially it happened to me as well, make sure to clear your browser cache

**Comment by bushvin** [comment]
It should be resolved with the latest release

**Comment by Switch123456789** [comment]
Yep, it's working like a charm now :)

Sorry I am late, my SSD died and my backups were old, so I had to set up HA all over again and redo all the lost work :sob: pure pain!
