### ISSUE TITLE
Detected code that calls async_forward_entry_setup without awaiting

### ISSUE THREAD

**Issue by ondras12345** [bushvin/hass-integrations#70]
Detected code that calls async_forward_entry_setup for integration mopidy with title: Mopidy Ondra and entry_id: 1a159625479d19e1cf92ac50300b8a71, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

Integration version: v2.3.5
Home Assistant version: 2024.7.1

Probably unrelated but potentially useful: https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups/

**Comment by bushvin** [comment]
Fixed in 20efce1674768f2388611031fa4757a9ef797376

**Comment by bushvin** [comment]
The code is in the latest release
