### ISSUE TITLE
How does search work?

### ISSUE THREAD

**Issue by prjcarr** [bushvin/hass-integrations#9]
I noticed you have implemented the search API for this integration. Just wondering if you have any tips on implementing this in HA. I currently use the mini media player and it's working great, but I want to be able to search and play songs from the results.

Is there a component to make this work with a GUI?

**Comment by bushvin** [comment]
Hi @prjcarr 
The documentation details how to use the search function.

I suggest you have a look in the HASS `developers tools` >> `services` to finetune and learn how to use it properly.

Then you can create an input field and a button which calls the service using the falue of the input field to search.

**Comment by prjcarr** [comment]
Thanks @bushvin. I got it working via developer tools, however it wont fit my use case as searching youtube music renders many results and adding all results to the queue is not what I was after. It would be great to have a proper HA Mopidy search service that presents results and allows you to play them or add to the queue. Similar to how this Kodi add on works: https://github.com/jtbgroup/kodi-search-card

Could we make this a feature request? Not sure if the kodi search card could even be altered to create this?

**Comment by bushvin** [comment]
I see what you mean. But unfortunately mine is an integration, and not a card (like your example). So I'd need to write something completely new. For which, quite frankly, I do not have the time now. But I'll put it on my wishlist.

An alternative would be to install iris (or whichever frontend you fancy) on your mopidy server and present that through an iframe in HA.
